# Workflow to publish package to PyPI when a new tag is pushed

name: Publish to PyPI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-n-publish:
    name: Build and publish python package to PyPI
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: Set up python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install wheel 
      run: pip install wheel
        
    - name: Build binary wheel and source tarball
      run: python setup.py sdist bdist_wheel
        
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{secrets.pypi_passsword}}
